"""REST + OpenAPI transport for openbraid (Phase D D1).

Second transport over the same canonical URL space established in
Phase C. Six POST endpoints under `/api/...` mirror the FastMCP tool
surface 1:1; both transports call into the same impls in
`server/tool_impls.py` so they can't drift.

Auth: Bearer token over HTTPS for the four authed endpoints
(send_memo, list_inbox, read_memo, mark_read). The token is the same
`session_token` returned by `auth_with_pin` — works as MCP session
credential AND as REST Bearer.

OpenAPI 3.1 spec auto-generated by FastAPI at `/api/openapi.json`
(swagger UI at `/api/docs`). Designed for ChatGPT Custom GPT Actions
to consume directly.

Per Director ratification 2026-05-10 evening + strategist commentary
in the Phase D kickoff memo: REST is a transport, not a parallel
adapter — this module is exclusively wire-format adapters around the
shared impls.
"""

from __future__ import annotations

import secrets
from typing import Annotated

from fastapi import Depends, FastAPI, HTTPException, Request
from fastapi.responses import Response
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from pydantic import BaseModel, Field

from server.canonical_json import canonicalize, sha256_hex
from server.db import account_by_handle, artifact_by_account_and_slug
from server.tool_impls import (
    tool_add_position_impl,
    tool_auth_with_pin_impl,
    tool_bump_version_impl,
    tool_claim_org_create_impl,
    tool_claim_role_impl,
    tool_delete_position_impl,
    tool_list_inbox_impl,
    tool_mark_read_impl,
    tool_read_memo_impl,
    tool_send_memo_impl,
    tool_update_org_metadata_impl,
    tool_update_position_impl,
    tool_update_relationship_impl,
    tool_upload_org_impl,
)

api = FastAPI(
    title="openbraid REST",
    version="0.1.0",
    description=(
        "REST + OpenAPI transport for the openbraid memo service. "
        "Mirrors the six MCP tools (claim_role, auth_with_pin, "
        "send_memo, list_inbox, read_memo, mark_read) over JSON-over-"
        "HTTPS. Same PIN ceremony, same session_token, same memo "
        "store — different wire format. Designed for ChatGPT Custom "
        "GPT Actions and other OpenAPI consumers."
    ),
    openapi_version="3.1.0",
    docs_url="/docs",
    redoc_url=None,
)

_bearer = HTTPBearer(
    description="Session token from a successful `auth_with_pin` response.",
    auto_error=True,
)


def _client_session_id(request: Request) -> str:
    """Derive a client_session_id for REST callers.

    REST doesn't have an MCP session id; we mint a per-request UUID
    prefixed with `rest:` so audit data clearly distinguishes REST
    callers from MCP callers.
    """
    return f"rest:{secrets.token_hex(16)}"


# --- Pydantic request/response models ------------------------------------


class ClaimRoleRequest(BaseModel):
    position_url: str = Field(
        ...,
        description=(
            "Canonical OAGP position URL per orgdef-spec ba004ca. "
            "Three-segment form (`/account/org/position`) or "
            "two-segment sugar (`/account/position`, when the account "
            "hosts exactly one org). Full URLs with scheme, host-only "
            "forms, and bare paths all accepted."
        ),
        examples=["https://mcp.openbraid.app/scott/personal/personal-strategist"],
    )
    claim_what: str = Field(
        "read+write memos",
        description=(
            "Human-readable description of what's being authorized, "
            "shown in the openbraid panel so the user knows what "
            "they're approving."
        ),
    )


class ClaimRoleResponse(BaseModel):
    challenge_id: str
    expires_at: str
    message: str


class ClaimOrgCreateRequest(BaseModel):
    account_handle: str = Field(
        ...,
        description=(
            "The user's openbraid handle (email-localpart of their "
            "signup email)."
        ),
    )
    claim_what: str = Field(
        "Create a new openbraid organization",
        description=(
            "Human-readable description shown in the panel so the user "
            "understands what they're authorizing."
        ),
    )


class ClaimOrgCreateResponse(BaseModel):
    challenge_id: str
    expires_at: str
    message: str


class AuthWithPinRequest(BaseModel):
    challenge_id: str = Field(..., description="From a prior claim_role response.")
    pin: str = Field(
        ...,
        description=(
            "The 9-digit PIN the user reads from the openbraid panel. "
            "Whitespace stripped before validation so users can read "
            "the PIN in `123 456 789` form."
        ),
    )


class AuthWithPinResponse(BaseModel):
    session_token: str
    expires_at: str
    role: str


class SendMemoRequest(BaseModel):
    to_role: str = Field(
        ...,
        description=(
            "Recipient role name within the same account, OR the "
            "literal string `\"file\"` for a memo-to-file."
        ),
    )
    subject: str
    body: str
    body_ref: str | None = None
    action_required: bool = Field(
        False,
        description=(
            "Whether the memo requires a response. MUST be false when "
            "to_role=\"file\"."
        ),
    )
    in_reply_to: str | None = None
    thread_id: str | None = None


class SendMemoResponse(BaseModel):
    memo_id: str
    sent_at: str
    kind: str


class ListInboxRequest(BaseModel):
    status: str = Field("inbox", description="inbox | read | archived")
    limit: int = Field(50, description="Maximum memos to return.")
    folder: str | None = Field(
        None,
        description=(
            "None or 'inbox' for the directed-memo mailbox (default); "
            "'notes' for the authenticated role's notes folder."
        ),
    )


class MemoSummary(BaseModel):
    id: str
    from_position: str
    subject: str
    sent_at: str
    action_required: bool
    thread_id: str | None


class ListInboxResponse(BaseModel):
    memos: list[MemoSummary]


class ReadMemoRequest(BaseModel):
    memo_id: str


class MarkReadRequest(BaseModel):
    memo_id: str


class MarkReadResponse(BaseModel):
    ok: bool
    status: str


class UploadOrgRequest(BaseModel):
    org_slug: str = Field(
        ...,
        description=(
            "URL slug for the org (e.g. 'thingalog'). Used in canonical "
            "URLs: mcp.openbraid.app/<account>/<org_slug>/<position>. "
            "SHOULD match content.id; if not, the response sets "
            "slug_id_mismatch=true."
        ),
        examples=["thingalog"],
    )
    content: dict = Field(
        ...,
        description=(
            "The orgdef .opencatalog artifact as a parsed JSON object "
            "per orgdef SCHEMA v1.0.0. MUST contain catdef substrate "
            "envelope, orgdef MUST fields (id/name/version), and an "
            "items[] array of type-tagged entries (orgdef:Position, "
            "roledef:Job, optionally roledef:Role). Internal "
            "consistency enforced: every Position.job_definition.id "
            "resolves to a sibling roledef:Job item."
        ),
    )


class UploadOrgResponse(BaseModel):
    artifact_id: str
    org_slug: str
    version: str
    position_count: int
    job_count: int
    role_count: int
    byte_count: int
    slug_id_mismatch: bool


class UpdatePositionRequest(BaseModel):
    org_slug: str = Field(..., description="URL slug of the opencatalog to edit.")
    position_id: str = Field(..., description="Position item id inside items[].")
    patch: dict = Field(
        ...,
        description=(
            "Partial dict of position-level fields to overwrite. "
            "Arrays are replaced wholesale; caller composes the full "
            "new array."
        ),
    )
    expected_version: str | None = Field(
        None,
        description=(
            "Optional optimistic concurrency check. If set and the "
            "stored version doesn't match, the request rejects."
        ),
    )


class UpdateOrgMetadataRequest(BaseModel):
    org_slug: str = Field(..., description="URL slug of the opencatalog.")
    patch: dict = Field(
        ...,
        description=(
            "Partial dict of top-level org fields. Cannot touch "
            "catdef/orgdef/type envelope, id, or items[]."
        ),
    )
    expected_version: str | None = Field(None)


class BumpVersionRequest(BaseModel):
    org_slug: str = Field(..., description="URL slug of the opencatalog.")
    kind: str = Field(
        "patch",
        description="patch | minor | major",
    )
    expected_version: str | None = Field(None)


class EditReceipt(BaseModel):
    artifact_id: str
    org_slug: str
    version_before: str
    version_after: str
    edit_log_id: str | None = None
    applied_fields: list[str] = []


class AddPositionRequest(BaseModel):
    org_slug: str = Field(..., description="URL slug of the opencatalog.")
    position: dict = Field(
        ...,
        description=(
            "Full new orgdef:Position item dict (id, name, optional "
            "fields). Type set to 'orgdef:Position' if absent."
        ),
    )
    expected_version: str | None = Field(None)


class DeletePositionRequest(BaseModel):
    org_slug: str
    position_id: str
    expected_version: str | None = Field(None)


class UpdateRelationshipRequest(BaseModel):
    org_slug: str
    rtype: str = Field(
        ...,
        description=(
            "Relationship type: reports_to | directs | coordinates_with | "
            "validates_for | peer_of | implements_for | derives_from"
        ),
    )
    from_id: str
    to_id: str
    op: str = Field(
        "add",
        description="add | remove. Both idempotent.",
    )
    expected_version: str | None = Field(None)


# --- Routes -----------------------------------------------------------------


@api.post(
    "/claim_role",
    response_model=ClaimRoleResponse,
    summary="Begin a role-claim ceremony",
)
async def rest_claim_role(req: ClaimRoleRequest, request: Request) -> dict:
    try:
        return await tool_claim_role_impl(
            position_url=req.position_url,
            claim_what=req.claim_what,
            client_session_id=_client_session_id(request),
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e


@api.post(
    "/claim_org_create",
    response_model=ClaimOrgCreateResponse,
    summary="Begin a ceremony to create a new openbraid org for an account",
)
async def rest_claim_org_create(req: ClaimOrgCreateRequest, request: Request) -> dict:
    try:
        return await tool_claim_org_create_impl(
            account_handle=req.account_handle,
            claim_what=req.claim_what,
            client_session_id=_client_session_id(request),
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e


@api.post(
    "/auth_with_pin",
    response_model=AuthWithPinResponse,
    summary="Complete a role-claim ceremony via PIN",
)
async def rest_auth_with_pin(req: AuthWithPinRequest, request: Request) -> dict:
    try:
        return await tool_auth_with_pin_impl(
            challenge_id=req.challenge_id,
            pin=req.pin,
            client_session_id=_client_session_id(request),
        )
    except ValueError as e:
        raise HTTPException(status_code=401, detail=str(e)) from e


@api.post(
    "/send_memo",
    response_model=SendMemoResponse,
    summary="Send a memo (directed or memo-to-file)",
)
async def rest_send_memo(
    req: SendMemoRequest,
    creds: Annotated[HTTPAuthorizationCredentials, Depends(_bearer)],
) -> dict:
    try:
        return await tool_send_memo_impl(
            session_token=creds.credentials,
            to_role=req.to_role,
            subject=req.subject,
            body=req.body,
            body_ref=req.body_ref,
            action_required=req.action_required,
            in_reply_to=req.in_reply_to,
            thread_id=req.thread_id,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e


@api.post(
    "/list_inbox",
    response_model=ListInboxResponse,
    summary="List memos in the authenticated role's mailbox or notes folder",
)
async def rest_list_inbox(
    req: ListInboxRequest,
    creds: Annotated[HTTPAuthorizationCredentials, Depends(_bearer)],
) -> dict:
    try:
        return await tool_list_inbox_impl(
            session_token=creds.credentials,
            status=req.status,
            limit=req.limit,
            folder=req.folder,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e


@api.post(
    "/read_memo",
    summary="Read the full content of a memo by id",
)
async def rest_read_memo(
    req: ReadMemoRequest,
    creds: Annotated[HTTPAuthorizationCredentials, Depends(_bearer)],
) -> dict:
    try:
        return await tool_read_memo_impl(
            session_token=creds.credentials,
            memo_id=req.memo_id,
        )
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e)) from e


@api.post(
    "/mark_read",
    response_model=MarkReadResponse,
    summary="Mark a memo as read",
)
async def rest_mark_read(
    req: MarkReadRequest,
    creds: Annotated[HTTPAuthorizationCredentials, Depends(_bearer)],
) -> dict:
    try:
        return await tool_mark_read_impl(
            session_token=creds.credentials,
            memo_id=req.memo_id,
        )
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e)) from e


@api.post(
    "/upload_org",
    response_model=UploadOrgResponse,
    summary="Ingest an orgdef.openthing artifact as canonical content",
)
async def rest_upload_org(
    req: UploadOrgRequest,
    creds: Annotated[HTTPAuthorizationCredentials, Depends(_bearer)],
) -> dict:
    try:
        return await tool_upload_org_impl(
            session_token=creds.credentials,
            org_slug=req.org_slug,
            content=req.content,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e


@api.post(
    "/update_position",
    response_model=EditReceipt,
    summary="Patch a Position item's fields inside an opencatalog",
)
async def rest_update_position(
    req: UpdatePositionRequest,
    creds: Annotated[HTTPAuthorizationCredentials, Depends(_bearer)],
) -> dict:
    try:
        return await tool_update_position_impl(
            session_token=creds.credentials,
            org_slug=req.org_slug,
            position_id=req.position_id,
            patch=req.patch,
            expected_version=req.expected_version,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e


@api.post(
    "/update_org_metadata",
    response_model=EditReceipt,
    summary="Patch catalog-level org metadata (mission, vision, etc.)",
)
async def rest_update_org_metadata(
    req: UpdateOrgMetadataRequest,
    creds: Annotated[HTTPAuthorizationCredentials, Depends(_bearer)],
) -> dict:
    try:
        return await tool_update_org_metadata_impl(
            session_token=creds.credentials,
            org_slug=req.org_slug,
            patch=req.patch,
            expected_version=req.expected_version,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e


@api.post(
    "/bump_version",
    response_model=EditReceipt,
    summary="Explicit semver bump without other changes",
)
async def rest_bump_version(
    req: BumpVersionRequest,
    creds: Annotated[HTTPAuthorizationCredentials, Depends(_bearer)],
) -> dict:
    try:
        return await tool_bump_version_impl(
            session_token=creds.credentials,
            org_slug=req.org_slug,
            kind=req.kind,
            expected_version=req.expected_version,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e


@api.post(
    "/add_position",
    response_model=EditReceipt,
    summary="Add a new orgdef:Position item to an opencatalog",
)
async def rest_add_position(
    req: AddPositionRequest,
    creds: Annotated[HTTPAuthorizationCredentials, Depends(_bearer)],
) -> dict:
    try:
        return await tool_add_position_impl(
            session_token=creds.credentials,
            org_slug=req.org_slug,
            position=req.position,
            expected_version=req.expected_version,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e


@api.post(
    "/delete_position",
    response_model=EditReceipt,
    summary="Delete an orgdef:Position item (blocked by active sessions)",
)
async def rest_delete_position(
    req: DeletePositionRequest,
    creds: Annotated[HTTPAuthorizationCredentials, Depends(_bearer)],
) -> dict:
    try:
        return await tool_delete_position_impl(
            session_token=creds.credentials,
            org_slug=req.org_slug,
            position_id=req.position_id,
            expected_version=req.expected_version,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e


@api.post(
    "/update_relationship",
    response_model=EditReceipt,
    summary="Add or remove a relationships[] entry",
)
async def rest_update_relationship(
    req: UpdateRelationshipRequest,
    creds: Annotated[HTTPAuthorizationCredentials, Depends(_bearer)],
) -> dict:
    try:
        return await tool_update_relationship_impl(
            session_token=creds.credentials,
            org_slug=req.org_slug,
            rtype=req.rtype,
            from_id=req.from_id,
            to_id=req.to_id,
            op=req.op,
            expected_version=req.expected_version,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e


@api.get(
    "/export/{account}/{org_slug}",
    summary="Export the stored orgdef .opencatalog artifact byte-equivalent",
    description=(
        "Serves the stored opencatalog content as canonical JSON. The "
        "response is `application/json; charset=utf-8` with an "
        "`X-Content-SHA256` header carrying the lowercase-hex SHA-256 "
        "of the canonical bytes (keys sorted, compact separators, "
        "UTF-8). Public read — no Bearer required; mirrors the boot URL "
        "stance that orgdef content is public per OAGP family v0 posture."
    ),
)
async def rest_export_org(account: str, org_slug: str) -> Response:
    acct = account_by_handle(account)
    if not acct:
        raise HTTPException(status_code=404, detail="account not found")
    artifact = artifact_by_account_and_slug(acct["id"], org_slug)
    if not artifact:
        raise HTTPException(status_code=404, detail="org artifact not found")

    content = artifact["content"]
    body = canonicalize(content)
    digest = sha256_hex(content)
    return Response(
        content=body,
        media_type="application/json",
        headers={
            "X-Content-SHA256": digest,
            "Cache-Control": "public, max-age=60",
        },
    )
