"""REST + OpenAPI transport for openbraid (Phase D D1).

Second transport over the same canonical URL space established in
Phase C. Six POST endpoints under `/api/...` mirror the FastMCP tool
surface 1:1; both transports call into the same impls in
`server/tool_impls.py` so they can't drift.

Auth: Bearer token over HTTPS for the four authed endpoints
(send_memo, list_inbox, read_memo, mark_read). The token is the same
`session_token` returned by `auth_with_pin` — works as MCP session
credential AND as REST Bearer.

OpenAPI 3.1 spec auto-generated by FastAPI at `/api/openapi.json`
(swagger UI at `/api/docs`). Designed for ChatGPT Custom GPT Actions
to consume directly.

Per Director ratification 2026-05-10 evening + strategist commentary
in the Phase D kickoff memo: REST is a transport, not a parallel
adapter — this module is exclusively wire-format adapters around the
shared impls.
"""

from __future__ import annotations

import secrets
from typing import Annotated

from fastapi import Depends, FastAPI, HTTPException, Request
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from pydantic import BaseModel, Field

from server.tool_impls import (
    tool_auth_with_pin_impl,
    tool_claim_role_impl,
    tool_list_inbox_impl,
    tool_mark_read_impl,
    tool_read_memo_impl,
    tool_send_memo_impl,
    tool_upload_org_impl,
)

api = FastAPI(
    title="openbraid REST",
    version="0.1.0",
    description=(
        "REST + OpenAPI transport for the openbraid memo service. "
        "Mirrors the six MCP tools (claim_role, auth_with_pin, "
        "send_memo, list_inbox, read_memo, mark_read) over JSON-over-"
        "HTTPS. Same PIN ceremony, same session_token, same memo "
        "store — different wire format. Designed for ChatGPT Custom "
        "GPT Actions and other OpenAPI consumers."
    ),
    openapi_version="3.1.0",
    docs_url="/docs",
    redoc_url=None,
)

_bearer = HTTPBearer(
    description="Session token from a successful `auth_with_pin` response.",
    auto_error=True,
)


def _client_session_id(request: Request) -> str:
    """Derive a client_session_id for REST callers.

    REST doesn't have an MCP session id; we mint a per-request UUID
    prefixed with `rest:` so audit data clearly distinguishes REST
    callers from MCP callers.
    """
    return f"rest:{secrets.token_hex(16)}"


# --- Pydantic request/response models ------------------------------------


class ClaimRoleRequest(BaseModel):
    position_url: str = Field(
        ...,
        description=(
            "Canonical OAGP position URL per orgdef-spec ba004ca. "
            "Three-segment form (`/account/org/position`) or "
            "two-segment sugar (`/account/position`, when the account "
            "hosts exactly one org). Full URLs with scheme, host-only "
            "forms, and bare paths all accepted."
        ),
        examples=["https://mcp.openbraid.app/scott/personal/personal-strategist"],
    )
    claim_what: str = Field(
        "read+write memos",
        description=(
            "Human-readable description of what's being authorized, "
            "shown in the openbraid panel so the user knows what "
            "they're approving."
        ),
    )


class ClaimRoleResponse(BaseModel):
    challenge_id: str
    expires_at: str
    message: str


class AuthWithPinRequest(BaseModel):
    challenge_id: str = Field(..., description="From a prior claim_role response.")
    pin: str = Field(
        ...,
        description=(
            "The 9-digit PIN the user reads from the openbraid panel. "
            "Whitespace stripped before validation so users can read "
            "the PIN in `123 456 789` form."
        ),
    )


class AuthWithPinResponse(BaseModel):
    session_token: str
    expires_at: str
    role: str


class SendMemoRequest(BaseModel):
    to_role: str = Field(
        ...,
        description=(
            "Recipient role name within the same account, OR the "
            "literal string `\"file\"` for a memo-to-file."
        ),
    )
    subject: str
    body: str
    body_ref: str | None = None
    action_required: bool = Field(
        False,
        description=(
            "Whether the memo requires a response. MUST be false when "
            "to_role=\"file\"."
        ),
    )
    in_reply_to: str | None = None
    thread_id: str | None = None


class SendMemoResponse(BaseModel):
    memo_id: str
    sent_at: str
    kind: str


class ListInboxRequest(BaseModel):
    status: str = Field("inbox", description="inbox | read | archived")
    limit: int = Field(50, description="Maximum memos to return.")
    folder: str | None = Field(
        None,
        description=(
            "None or 'inbox' for the directed-memo mailbox (default); "
            "'notes' for the authenticated role's notes folder."
        ),
    )


class MemoSummary(BaseModel):
    id: str
    from_position: str
    subject: str
    sent_at: str
    action_required: bool
    thread_id: str | None


class ListInboxResponse(BaseModel):
    memos: list[MemoSummary]


class ReadMemoRequest(BaseModel):
    memo_id: str


class MarkReadRequest(BaseModel):
    memo_id: str


class MarkReadResponse(BaseModel):
    ok: bool
    status: str


class UploadOrgRequest(BaseModel):
    org_slug: str = Field(
        ...,
        description=(
            "URL slug for the org (e.g. 'thingalog'). Used in canonical "
            "URLs: mcp.openbraid.app/<account>/<org_slug>/<position>. "
            "SHOULD match content.id; if not, the response sets "
            "slug_id_mismatch=true."
        ),
        examples=["thingalog"],
    )
    content: dict = Field(
        ...,
        description=(
            "The orgdef .opencatalog artifact as a parsed JSON object "
            "per orgdef SCHEMA v1.0.0. MUST contain catdef substrate "
            "envelope, orgdef MUST fields (id/name/version), and an "
            "items[] array of type-tagged entries (orgdef:Position, "
            "roledef:Job, optionally roledef:Role). Internal "
            "consistency enforced: every Position.job_definition.id "
            "resolves to a sibling roledef:Job item."
        ),
    )


class UploadOrgResponse(BaseModel):
    artifact_id: str
    org_slug: str
    version: str
    position_count: int
    job_count: int
    role_count: int
    byte_count: int
    slug_id_mismatch: bool


# --- Routes -----------------------------------------------------------------


@api.post(
    "/claim_role",
    response_model=ClaimRoleResponse,
    summary="Begin a role-claim ceremony",
)
async def rest_claim_role(req: ClaimRoleRequest, request: Request) -> dict:
    try:
        return await tool_claim_role_impl(
            position_url=req.position_url,
            claim_what=req.claim_what,
            client_session_id=_client_session_id(request),
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e


@api.post(
    "/auth_with_pin",
    response_model=AuthWithPinResponse,
    summary="Complete a role-claim ceremony via PIN",
)
async def rest_auth_with_pin(req: AuthWithPinRequest, request: Request) -> dict:
    try:
        return await tool_auth_with_pin_impl(
            challenge_id=req.challenge_id,
            pin=req.pin,
            client_session_id=_client_session_id(request),
        )
    except ValueError as e:
        raise HTTPException(status_code=401, detail=str(e)) from e


@api.post(
    "/send_memo",
    response_model=SendMemoResponse,
    summary="Send a memo (directed or memo-to-file)",
)
async def rest_send_memo(
    req: SendMemoRequest,
    creds: Annotated[HTTPAuthorizationCredentials, Depends(_bearer)],
) -> dict:
    try:
        return await tool_send_memo_impl(
            session_token=creds.credentials,
            to_role=req.to_role,
            subject=req.subject,
            body=req.body,
            body_ref=req.body_ref,
            action_required=req.action_required,
            in_reply_to=req.in_reply_to,
            thread_id=req.thread_id,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e


@api.post(
    "/list_inbox",
    response_model=ListInboxResponse,
    summary="List memos in the authenticated role's mailbox or notes folder",
)
async def rest_list_inbox(
    req: ListInboxRequest,
    creds: Annotated[HTTPAuthorizationCredentials, Depends(_bearer)],
) -> dict:
    try:
        return await tool_list_inbox_impl(
            session_token=creds.credentials,
            status=req.status,
            limit=req.limit,
            folder=req.folder,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e


@api.post(
    "/read_memo",
    summary="Read the full content of a memo by id",
)
async def rest_read_memo(
    req: ReadMemoRequest,
    creds: Annotated[HTTPAuthorizationCredentials, Depends(_bearer)],
) -> dict:
    try:
        return await tool_read_memo_impl(
            session_token=creds.credentials,
            memo_id=req.memo_id,
        )
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e)) from e


@api.post(
    "/mark_read",
    response_model=MarkReadResponse,
    summary="Mark a memo as read",
)
async def rest_mark_read(
    req: MarkReadRequest,
    creds: Annotated[HTTPAuthorizationCredentials, Depends(_bearer)],
) -> dict:
    try:
        return await tool_mark_read_impl(
            session_token=creds.credentials,
            memo_id=req.memo_id,
        )
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e)) from e


@api.post(
    "/upload_org",
    response_model=UploadOrgResponse,
    summary="Ingest an orgdef.openthing artifact as canonical content",
)
async def rest_upload_org(
    req: UploadOrgRequest,
    creds: Annotated[HTTPAuthorizationCredentials, Depends(_bearer)],
) -> dict:
    try:
        return await tool_upload_org_impl(
            session_token=creds.credentials,
            org_slug=req.org_slug,
            content=req.content,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e


